### ISSUE TITLE
Sublime Text 3 Support

### ISSUE THREAD

**Issue by marcioAlmada** [chrisbreiding/ASCIIPresentation#2]
Why u no?

:smile:

**Comment by chrisbreiding** [comment]
Afraid I haven't given this much love recently. It wouldn't be in the spirit of Sublime Text to have frequent, continual development, would it? ;) 

Seriously though, I'll test out ST3 support and try to get it working soon.

**Comment by marcioAlmada** [comment]
Great. I still have ST2 installed just because of this awesome plugin :)

**Comment by chrisbreiding** [comment]
ST3 support has landed - enjoy!

**Comment by marcioAlmada** [comment]
Whoaa, that was fast. Thanks, @chrisbreiding!
